services:
  users.api:
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=users.db;Database=usersdb;Username=postgres;Password=postgres
      KeyCloak__AdminUrl: http://keycloak:8080/admin/realms/online_judge/
      KeyCloak__TokenUrl: http://keycloak:8080/realms/online_judge/protocol/openid-connect/token
      KeyCloak__ConfidentialClientId: online_judge-confidential-client
      KeyCloak__ConfidentialClientSecret: rO4xRoiYtfARePWXa8AUlEFuX9nhT8b1
      KeyCloak__PublicClientId: online_judge-public-client
      KeyCloak__Audience: account
      KeyCloak__Authority: http://keycloak:8080/realms/online_judge
      Logging__LogLevel__Default: Information
      Jaeger__OTEL_EXPORTER_OTLP_ENDPOINT: http://logging-jaeger:4317/
    depends_on:
      users.db:
        condition: service_healthy

  corejudge.db: 
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: corejudgedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  users.db:
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  logging-jaeger:
    container_name: logging.jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"

  corejudge.api:
    user: root
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=corejudge.db;Database=corejudgedb;Username=postgres;Password=postgres
      KeyCloak__AdminUrl: http://keycloak:8080/admin/realms/online_judge/
      KeyCloak__TokenUrl: http://keycloak:8080/realms/online_judge/protocol/openid-connect/token
      KeyCloak__ConfidentialClientId: online_judge-confidential-client
      KeyCloak__ConfidentialClientSecret: rO4xRoiYtfARePWXa8AUlEFuX9nhT8b1
      KeyCloak__PublicClientId: online_judge-public-client
      KeyCloak__Audience: account
      KeyCloak__Authority: http://keycloak:8080/realms/online_judge
      Logging__LogLevel__Default: Information
      Jaeger__OTEL_EXPORTER_OTLP_ENDPOINT: http://logging-jaeger:4317/
      ConnectionStrings__Redis: caching:6379,password=StrongRedisPassword123
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      ElasticSearch__Uri: http://elasticsearch:9200
      RUN_CODE_SCRIPT_PATH: /app/Premitives/run_code.sh
      DOCKER_HOST_URI: unix:///var/run/docker.sock
    depends_on:
      corejudge.db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      caching:
        condition: service_healthy

  caching:
    ports:
      - "6379:6379"

  community.mongo:
    ports:
      - "27017:27017"

  community.api:
    ports:
      - "5004:8080"
    environment:
      MongoDB__ConnectionString: mongodb://admin:StrongMongoPassword123@community.mongo:27017
      MongoDB__DatabaseName: CommunityDb
    
      Minio__Endpoint: minio:9000 # for connection within the Docker network
      Minio__PublicEndpoint: localhost:9000 # for external access (e.g., presigned URLs)
      Minio__AccessKey: admin
      Minio__SecretKey: password
      Minio__BucketName: community-service
      Minio__UseSSL: "false"
    
    depends_on:
      community.mongo:
        condition: service_healthy
      minio:
        condition: service_healthy

  api.gateway:
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KeyCloak__AdminUrl: http://keycloak:8080/admin/realms/online_judge/
      KeyCloak__TokenUrl: http://keycloak:8080/realms/online_judge/protocol/openid-connect/token
      KeyCloak__ConfidentialClientId: online_judge-confidential-client
      KeyCloak__ConfidentialClientSecret: rO4xRoiYtfARePWXa8AUlEFuX9nhT8b1
      KeyCloak__PublicClientId: online_judge-public-client
      KeyCloak__Audience: account
      KeyCloak__Authority: http://keycloak:8080/realms/online_judge
      Logging__LogLevel__Default: Information
      Jaeger__OTEL_EXPORTER_OTLP_ENDPOINT: http://logging-jaeger:4317/
    depends_on:
      users.api:
        condition: service_healthy
      corejudge.api:
        condition: service_healthy
    restart: unless-stopped

  elasticsearch:
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  collaboration.api:
    ports:
      - "5003:8080"
    volumes:
      - ./Services/Collaboration:/app
    command: ["npm", "run", "dev"]

  minio:
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: http://localhost:9000